Document HorizonClient and Models
Baseflow/stellar-rust-sdk pull request #19
Opened 2023-12-11 10:44 UTC by pnehkan

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Introduces elaborate documentation for the HorizonClient and Models.

Furthermore:
* Moves HorizonClient into root, since it was the only struct in the module. This made for more natural documentation.
* Moves the XDR test into the Models testing suite.
* Removes the now empty horizon_client and xdr modules.

### :arrow_heading_down: What is the current behavior?

### :new: What is the new behavior (if this is a feature change)?

### :boom: Does this PR introduce a breaking change?

### :bug: Recommendations for testing

### :memo: Links to relevant issues/docs

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines 
- [ ] Relevant documentation was updated
- [ ] Rebased onto current main

2023-12-12 15:06 UTC, tluijken requested changes

2023-12-12 15:06 UTC, tluijken commented on src/horizon_client.rs
> +    /// let request: AccountsRequest<NoSponsor, Signer, NoAsset, NoLiquidityPool> = AccountsRequest::new()
I wonder if people would annotate their variable like this. Perhaps to not make it too complicated, just stick with 
```suggestion
    /// let request = AccountsRequest::new()
```

2023-12-12 15:06 UTC, tluijken commented on src/horizon_client.rs
> +    /// # use stellar_rust_sdk::accounts::accounts_request::Signer;
If we can agree on the suggestion below, we might not have to add the `Signer` using, and just stick with the `prelude`.

2023-12-12 15:06 UTC, tluijken commented on src/horizon_client.rs
> +    ///
We should add en example here too, just like the `get_single_account` request.

2023-12-12 15:06 UTC, tluijken commented on src/horizon_client.rs
>      pub async fn get_all_claimable_balances(
We should add en example here too, just like the `get_single_account` request.

2023-12-12 15:06 UTC, tluijken commented on src/horizon_client.rs
> +    ///
We should add en example here too, just like the `get_single_account` request.

2023-12-12 15:06 UTC, tluijken commented on src/horizon_client.rs
> +    ///  let request: SingleClaimableBalanceRequest<ClaimableBalanceId> = SingleClaimableBalanceRequest::new()
We should probably omit the annotation, as we want our states to eventually become internal

2023-12-12 15:06 UTC, tluijken commented on src/horizon_client.rs
> +    /// let request: SingleAccountRequest<AccountId> = SingleAccountRequest::new()
We should probably omit the annotation, as we want our states to eventually become internal

2023-12-12 15:06 UTC, tluijken commented on src/lib.rs
> +    /// parameters, or all properties are `None`, an empty string is returned.
Dit laatste is alleen waar voor de implementation van `Vec<Option<T>>`. Voor de algemene generic is dit niet persee waar.

2023-12-13 10:53 UTC, pnehkan commented on src/horizon_client.rs
> +    /// # use stellar_rust_sdk::accounts::accounts_request::Signer;
Removed the Signer import :+1:

2023-12-13 10:53 UTC, pnehkan commented on src/horizon_client.rs
> +    ///
Added an example!

2023-12-13 10:53 UTC, pnehkan commented on src/horizon_client.rs
>      pub async fn get_all_claimable_balances(
Added an example!

2023-12-13 10:53 UTC, pnehkan commented on src/horizon_client.rs
> +    ///
Added an example!

2023-12-13 10:53 UTC, pnehkan commented on src/horizon_client.rs
> +    ///  let request: SingleClaimableBalanceRequest<ClaimableBalanceId> = SingleClaimableBalanceRequest::new()
Removed the annotation :+1:

2023-12-13 10:53 UTC, pnehkan commented on src/horizon_client.rs
> +    /// let request: SingleAccountRequest<AccountId> = SingleAccountRequest::new()
Removed the annotation :+1:

2023-12-13 10:55 UTC, pnehkan commented on src/lib.rs
> +    /// parameters, or all properties are `None`, an empty string is returned.
Ik heb nu deze subtlety (die wel belangrijk is) verwerkt in de documentatie zodat duidelijk is dat deze implementatiedetails/return contents alleen gelden bij de specifieke implementatie voor `Vec<Option<T>>`. Ik denk dat het zo beter is, misschien kun je er even naar kijken? :+1:

2023-12-21 10:29 UTC, tluijken requested changes
I think we can omit the code examples on the mod exports. For specific calls, the horizonClient already provides the same examples per function.

2023-12-21 10:29 UTC, tluijken commented on src/lib.rs
> +///
Does this documentation belong to the accounts module? I believe this exact same documentation is already provided at https://github.com/Baseflow/stellar-rust-sdk/blob/4cf167e4dee31fdf8b9f31895c0b6a12dd9a2235/src/horizon_client/horizon_client.rs#L44. The module itself contains of course more than the provided documentation here.

2023-12-21 10:29 UTC, tluijken commented on src/lib.rs
> +/// # }
This also has been documentated at HorizonClient::getAllAssets. The module itself provides more functionality, so it should not be documented here for a specific endpoint I believe.

2023-12-21 10:29 UTC, tluijken commented on src/lib.rs
> +/// by the Horizon API. For example, it has a [`HorizonClient::get_account_list`](crate::horizon_client::HorizonClient::get_account_list)
This refers to the get_account_list fn, while the example shows the AllAssetsRequest example.

2023-12-21 10:35 UTC, tluijken requested changes
Ik neem die documentatie nog even over

2023-12-21 10:35 UTC, tluijken commented on src/lib.rs
> +    /// parameters, or all properties are `None`, an empty string is returned.
Ik zou m verplaatsen naar de documentatie van de implementatie. De filtering is specifiek voor die implementatie, maar de trait dwingt het niet af.

2023-12-21 12:23 UTC, tluijken commented
Already processed with PR #21

2023-12-21 12:23 UTC, closed without merging