Effects for liquidity pools endpoint
Baseflow/stellar-rust-sdk pull request #35
Opened 2024-02-13 12:04 UTC by LeonardTibben

2024-02-13 13:14 UTC, pnehkan requested changes

2024-02-13 13:14 UTC, pnehkan commented on src/effects/effects_for_account_request.rs
> +    fn test_ledgers_request_with_params() {
Deze naam van de test klopt niet helemaal :eyes:

2024-02-13 13:14 UTC, pnehkan commented on src/horizon_client.rs
>      pub async fn get_all_effects(
Awesome dat je ook hier documentatie hebt toegevoegd :)

2024-02-13 13:14 UTC, pnehkan commented on src/horizon_client.rs
> +            EffectsForLiquidityPoolsRequest::new().set_limit(2).unwrap();
Zou je ook een test kunnen toevoegen waarbij je test met een liquidity pool ID?  :+1:

2024-02-14 08:46 UTC, pnehkan requested changes

2024-02-14 08:46 UTC, pnehkan commented on src/effects/effects_for_liquidity_pools_request.rs
> +}
Als ik de documentatie lees lijkt de URL anders opgebouwd te worden, maar deze variant lijkt ook te werken. Hoe kan dit? Krijg je dan wel de informatie die je graag wilt?
Zouden we vrijdag ook met Thomas kunnen bespreken :+1:

2024-02-14 08:46 UTC, pnehkan commented on src/effects/mod.rs
> +}
Misschien moeten we deze er nog even uit gooien (die had ik alleen toegevoegd om de code coverage omhoog te krijgen :see_no_evil: )

2024-02-26 10:16 UTC, tluijken requested changes
I vraag m.b.t. documentatie. Verder ziet het er goed uit!

2024-02-26 10:16 UTC, tluijken commented on src/effects/effects_for_liquidity_pools_request.rs
> +pub struct EffectsForLiquidityPoolRequest {
Ik mis hier nog documentatie rondom de `EffectsForLiquidityPoolRequest` zelf.

Net als bij `SingleAccountRequest<I>`, zie je dat Eline niet alleen documentatie heeft toegevoegd, maar ook referenties naar de Horizon API Endpoint, code examples die getest worden met cargo test (doctest).

Dit zou eigenlijk standaard voor alle publieke structs moeten zijn.

Zo mis ik dit ook voor `EffectsForAccountRequest` bijv. Zit niet in deze PR, maar mag er wel bij wat mij betreft.

2024-02-26 10:29 UTC, tluijken approved these changes

2024-02-26 10:43 UTC, merged