Fix code coverage script
Baseflow/stellar-rust-sdk pull request #74
Opened 2024-05-14 13:12 UTC by kevin-pease

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Updates the shell script for checking the code coverage. Includes minor test value updates to prevent a blocked PR.

Fixes #67.

### :arrow_heading_down: What is the current behavior?
The script fails because it cannot find input files. 

### :new: What is the new behavior (if this is a feature change)?
A simple directory change command at the beginning of the script.

### :boom: Does this PR introduce a breaking change?
No.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines 
- [x] Relevant documentation was updated
- [x] Rebased onto current main

2024-05-14 13:22 UTC, tluijken approved these changes

2024-05-14 13:25 UTC, tluijken requested changes

2024-05-14 13:25 UTC, tluijken commented on code-coverage.sh
> +cd stellar_rust_sdk
Dit kan, maar is niet zo fraai. Mooiste is om `cargo test` met een manifest file aan te roepen. Mocht je relatieve paden met dependencies hebben (zoals de derive crate) dan werkt dat ook mooi. Zie onderstaande suggestie.

2024-05-14 13:25 UTC, tluijken commented on code-coverage.sh
>  CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo test
```suggestion
CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo test --manifest-path=stellar_rust_sdk/Cargo.toml
```
Dit is ook in lijn met de github workflows voor dit project.

2024-05-24 10:35 UTC, LeonardTibben approved these changes

2024-05-27 11:14 UTC, tluijken approved these changes

2024-05-30 09:45 UTC, merged